# fly.toml app configuration file generated for blox on 2024-09-02T18:10:11+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blox'
primary_region = 'ams'
swap_size_mb = 512

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'off'
auto_start_machines = false
min_machines_running = 1
processes = ['app']


[[vm]]
size = 'shared-cpu-1x'

[env]
NODE_ENV = 'development'
SECURE_PORT = '8443'
PORT = '3000'
WALLET_ADDRESS = '0x1Fb0C631dF78c4Bb723e293D04d687bc0cEfc869'
DB_PASSWORD = 'uLzWTgZNCXHt8F93kYn64m'
DB_NAME = 'blox_public'
DB_HOST = 'blox-db.internal'
DB_USER = 'root'
